[book]
authors = ["JordiMateoUdL"]
language = "en"
multilingual = false
src = "src"
title = "HandsOns en Sistemes Operatius per a estudiants del Grau en Enginyeria Inform√†tica"

[output.html.playground]
editable = true